### ISSUE TITLE
CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kitsunenosaraT** [kitsunenosaraT/Mozilla-Italia-l10n-guide#10]

**Comment by gialloporpora** [comment]
@kitsunenosarat,
credi sia da aggiungere solo un'appendice al documento relativo a alcune 
specifiche del progetto o riscriverlo tutto incentrandolo proprio sul 
come collaborare alla guida?

**Comment by kitsunenosaraT** [comment]
Scusa se ti rispondo solo ora, mi ero persa la notifica 😓 
"Come collaborare alla guida", secondo me è coperto a sufficienza in CONTRIBUTING.
Io pensavo più a una breve appendice incentrata sull'aspetto etico e sui rapporti da tenere con gli altri collaboratori. Ti faccio alcuni piccoli esempi per spiegarmi meglio…
- quando ci si propone per un progetto, ci si prende l'impegno di mantenerlo aggiornato nel tempo, e non di sparire dopo la prima traduzione (o peggio di lasciarla a metà)
- quando si traduce per Mozilla Italia bisogna fare lo sforzo di adeguarsi al nostro stile (leggere la documentazione, fare ricerche terminologiche utilizzando il glossario e le TM a disposizione)
- in fase di revisione, il revisore deve spiegare con pazienza la motivazione delle sue correzioni e fare critiche costruttive, senza offendere o mortificare il traduttore per il suo livello di inglese o italiano. Quando possibile offrirà anche consigli o risorse per migliorare la tecnica del traduttore.
- in fase di revisione il traduttore non può semplicemente ignorare le correzioni. Se una correzione non gli piace, invece di insistere sulla propria versione, offre una terza alternativa  (in quanto se un altro madrelingua nota qualcosa di innaturale nella tua traduzione, vuol dire che probabilmente si può fare di meglio)
- Se il traduttore pensa che una correzione sia fuori luogo, lo fa notare e spiega le sue ragioni in modo puntuale ed educato.
- Un nuovo traduttore non deve scoraggiarsi se al suo primo compito le correzioni sono numerose, né prenderla sul personale per le correzioni stilistiche a testi linguisticamente giusti. Nessuno sta contestando la sua capacità di esprimersi in italiano o pretendendo di insegnargli a scrivere, si tratta solo di uniformare stilisticamente il testo ai canoni dell'organizzazione.

Insomma, pensavo a qualcosa su questa linea.

**Comment by kitsunenosaraT** [comment]
A huge thank you to @gialloporpora for writing in English our localizer-specific CoC. 👍 
I'm closing the issue at last.
