### ISSUE TITLE
Translating Activity Stream in Tamil

### ISSUE THREAD

**Issue by kitsunenosaraT** [kitsunenosaraT/Mozilla-Italia-l10n-guide#52]
This is an experiment for the #mozsprint.
@surentharan is going to translate the short project Activity Stream in Tamil

**URL:** https://pontoon.mozilla.org/ta/activity-stream-new-tab/
**File type:**`properties`
**Tool:** Pontoon

Welcome onboard surentharan, and have a fun time translating! 🎉

**Comment by surentharan** [comment]
Hey there , Its a great time in contributing to the project

**Comment by surentharan** [comment]
Completed the project

**Comment by kitsunenosaraT** [comment]
Thank you @surentharan 
This was an important contribution, I'm glad you were able to advance the Tamil localization during this Global Sprint.

**Comment by kitsunenosaraT** [comment]
@surentharan I’ve just emailed the admin for Tamil language to inform him of your contributions, so that the work you did today may be acknowledged!

**Comment by thangamani-arun** [comment]
@kitsunenosaraT Thanks for notifying me about @surentharan's contribution.  I have reviewed all the strings. Kindly let us know, how to test the same. 

Thanks @surentharan for your contribution, Please keep in touch with [Tamil L10n-team](https://wiki.mozilla.org/L10n:Teams:ta) through mailing list.

**Comment by kitsunenosaraT** [comment]
@thangamani-arun Thank you for accepting surentharan's translations!
I'm forwarding your question to @flodolo What is the standard procedure to test translation for [Activity Stream](https://pontoon.mozilla.org/ta/activity-stream-new-tab/)?

**Comment by flodolo** [comment]
https://github.com/mozilla/activity-stream#installing (dev build)

**Comment by kitsunenosaraT** [comment]
@flodolo Mercì :grinning:
